on: [push, pull_request]
name: 'Upload Image to ECR'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing the images with GitHub OIDC Token
      attestations: write
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Generate GHCR Metadata
        id: ghcr_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/hello
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and Push to GHCR
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.ghcr_meta.outputs.tags }}
          labels: ${{ steps.ghcr_meta.outputs.labels }}
          cache-to: type=inline

      - name: Login to Amazon ECR
        id: login-ecr
        shell: bash
        run: |
          echo 'registry=123456789012.ecr-fips.us-gov-west-1.amazonaws.com' >> "$GITHUB_ENV"

      - name: Generate Docker Metadata for ECR
        if: github.ref == 'refs/heads/main'
        id: ecr_meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}/hello
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      # # Checks if the ECR repository exists, and creates it if it does not
      # - name: Create ECR Repository
      #   id: create_repo
      #   shell: bash
      #   run: |
      #     aws ecr describe-repositories --repository-names ${REPO_NAME} || \
      #     aws ecr create-repository --repository-name ${REPO_NAME} \
      #                               --image-scanning-configuration scanOnPush=true

      - name: Build and Push to AWS ECR
        id: push_ecr
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.ecr_meta.outputs.tags }}
          labels: ${{ steps.ecr_meta.outputs.labels }}
          cache-from: type=inline

      - name: Print ECR tags
        shell: bash
        run: echo "${{ steps.ecr_meta.outputs.tags }}"